# Generated by Django 3.2.3 on 2021-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='News')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('photo', models.ImageField(upload_to='News', verbose_name='Photo')),
                ('about', models.TextField(verbose_name='About')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
