# Generated by Django 3.2.3 on 2021-05-25 07:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name Category')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='News Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='Status')),
                ('author', models.CharField(default='One Planet', max_length=30, verbose_name='Author')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('picture', models.ImageField(default='news/breaking.jpg', upload_to='news', verbose_name='Picture default breaking.jpg')),
                ('additional_category', models.ManyToManyField(blank=True, related_name='additional', to='polls.Category', verbose_name='Additional Categories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='polls.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
